"""Initial Migration

Revision ID: a12f73765532
Revises: 
Create Date: 2023-10-25 15:03:45.037723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12f73765532'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('img')
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mimetype', sa.Text(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('mimetype', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('mimetype')
        batch_op.drop_column('img')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('mimetype')
        batch_op.drop_column('img')

    op.create_table('img',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('img', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('mimetype', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
